on: [push]
      
name: "Testing actions"
jobs:
  testing_actions:
    name: Testing Actions
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "Hello"
      - with:
        - name: artefact
        - path: lib/main.dart 

